basePath: /
definitions:
  models.Product:
    properties:
      name:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    name: API Support
  description: Fiber Swagger Example
  termsOfService: http://swagger.io/terms/
  title: Example API
  version: "1.0"
paths:
  /api/v1/:
    get:
      consumes:
      - application/json
      description: Returns the health status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get API health status
      tags:
      - Health
  /api/v1/products:
    get:
      consumes:
      - application/json
      description: Returns a list of products available in the store
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
      summary: Get list of products
      tags:
      - Products
swagger: "2.0"
